version: "3.9"
services:
  hypebot:
    container_name: hypebot
    image: sonastea/hypebot:latest
    build:
      context: .
      dockerfile: ./docker/hypebot/Dockerfile
    restart: unless-stopped
    environment:
      - TOKEN
    volumes:
      - "./songs:/app/songs"
      - "./hypebase.db:/app/hypebase.db"

  hypeserver:
    container_name: hypeserver
    image: sonastea/hypeserver:latest
    build:
      context: .
      dockerfile: ./docker/hypeserver/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - hypebot
