version: "3.8"

services:
  hypebot:
    container_name: hypebot
    image: "ghcr.io/sonastea/hypebot:latest"
    env_file: .env
    build:
      context: .
      args:
        TOKEN: ${TOKEN}
        DISABLED_COMMANDS: ${DISABLED_COMMANDS}
      dockerfile: ./docker/hypebot/Dockerfile
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
    restart: unless-stopped
    networks: ["caddy_default"]
    environment:
      - TOKEN
      - DISABLED_COMMANDS
    volumes:
      - "./songs:/app/songs"
      - "./hypebase.db:/app/hypebase.db"

  hypeserver:
    container_name: hypeserver
    image: "ghcr.io/sonastea/hypeserver:latest"
    build:
      context: .
      dockerfile: ./docker/hypeserver/Dockerfile
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
    restart: unless-stopped
    networks: ["caddy_default"]
    ports:
      - "3000:3000"
    depends_on:
      - hypebot
    volumes:
      - "./hypebase.db:/app/hypebase.db:ro"

networks:
  caddy_default:
    external: true
