version: "3.9"
services:
  hypebot:
    container_name: hypebot
    image: "ghcr.io/sonastea/hypebot:master"
    build:
      context: .
      args:
        TOKEN: ${TOKEN}
      dockerfile: ./docker/hypebot/Dockerfile
    restart: unless-stopped
    networks: ["caddy_default"]
    environment:
      - TOKEN
    volumes:
      - "./songs:/app/songs"
      - "./hypebase.db:/app/hypebase.db"

  hypeserver:
    container_name: hypeserver
    image: "ghcr.io/sonastea/hypeserver:master"
    build:
      context: .
      dockerfile: ./docker/hypeserver/Dockerfile
    restart: unless-stopped
    networks: ["caddy_default"]
    ports:
      - "3000:3000"
    depends_on:
      - hypebot
    volumes:
      - "./hypebase.db:/app/hypebase.db"

networks:
  caddy_default:
    external: true
